# Setup
title:               'Maii learning journal'
tagline:             'Stuff I learn to build stuff'
description:         'Maii as in "my"'
url:                 'https://eamesa.github.io/'
baseurl:             'maii-journal/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ernesto Amador Mesa
  url:               https://twitter.com/eamadorm
  email:             eamadorm@chicagobooth.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
